version: "3.3"
services:
  notebook:
    container_name: "fix_amounts"
    build: .
    # ポートの設定("ホスト：コンテナ")
    ports:
    # 4545だと自分のローカルと被るために1919にしました。
      - "1919:8888"
    # ボリューム(データの永続化の場所)の設定(ホスト:コンテナ)
    # ホスト内のworkディレクトリとコンテナ内の/workディレクトリが紐づいているイメージ
    # どうして/home/jovyan/workにマウントしてるかは元のイメージ(base-notebook)作ったやつに聞け
    volumes:
      - ./work:/home/jovyan/work