version: "3.3"
services:
  notebook:
    image: mecab-base-notebook
    container_name: "exchange_ingredients"
    build: .
    # ボリューム(データの永続化の場所)の設定(ホスト:コンテナ)
    # ホスト内のworkディレクトリとコンテナ内の/home/joyyan/workディレクトリが紐づいているイメージ
    # どうして/home/jovyan/workにマウントしてるかは元のイメージ(base-notebook)作ったやつに聞け
    volumes:
      - ./work:/home/jovyan/work